task: multitask

dataset:
  name: census-income-sample
  path: examples/ranking/data/census-income

model:
  name: ESMM
  params:
    embed_dim: 16
    cvr_mlp_dims:
      - 16
      - 8
    ctr_mlp_dims:
      - 16
      - 8

trainer:
  epochs: 1
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 0.0001
  earlystop_patience: 10
  device: cpu
  seed: 2022

output_dir: benchmark_results/multitask/census_esmm
