ko_fi: kemuling
custom:
  - https://afdian.com/a/kemuling
  - https://github.com/datawhalechina/torch-rechub/blob/main/.github/wechat_sponsor.png
  - https://github.com/datawhalechina/torch-rechub/blob/main/.github/alipay_sponsor.png
